name: React Smart Build Check


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest 

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4

    
    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm' 

    
    - name: Install Project Dependencies
      run: npm install

    
    - name: Compile and Build React App
      run: npm run build